### ISSUE TITLE
Prevent dots from overlapping

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#113]
People who have the same zip code have dots in the exact same location...

**Comment by kmcostel** [comment]
Add some noise to geocoding results; or somehow get dots with the same coordinates to show both their popups on click

**Comment by graceyin1218** [comment]
Not quite preventing dots from overlapping, but if you click on a cluster of markers that are too close to each other, they will expand so you can view each marker individually.

https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet

**Comment by graceyin1218** [comment]
The Spiderfier only works with markers (circleMarker inherits from circle, not marker 😢 ), and making custom red-dot markers creates many performance issues (speed and prettiness - you can uncomment line 385 in map.js if you're curious).

So... tradeoff. Being able to view all overlapping markers is pretty important...
