### ISSUE TITLE
Spiderfier interferes with marker removal

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#123]
If you draw a box, spiderfy some markers (so some of them now lie outside the box), and then remove the box, then the spiderfied markers that were outside the box aren't removed.

**Comment by kmcostel** [comment]
The spiderfy thing must do what it does by changing the coordinates of the marker on the map. So when leaflet searches inside the shape it will think it is outside of it. The logic right now is to keep any marker that was not in a deleted region. The logic could be changed to only keep markers outside of deleted regions and still inside of other search regions.

**Comment by kmcostel** [comment]
Or what should have been done in first place... to only keep markers contained in regions still on map.
