### ISSUE TITLE
Setup production

### ISSUE THREAD

**Issue by dmcassel** [marklogic/eauser-geomapper#131]
Create deploy/prod.properties. In that file:

- set the app-port to 8050 and the xcc-port to 8051
- leave password blank: `password=`

Bootstrap and deploy to prod.

**Comment by kmcostel** [comment]
Should app-name=eauser-geomapper-prod instead?

**Comment by dmcassel** [comment]
that was a typo -- you can leave app-name out of prod.properties all together and rely on the default value instead. I'll fix that in the description.
