### ISSUE TITLE
Create selection menu for predefined search regions

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#132]

**Comment by dmcassel** [comment]
Whatever regions are displayed should be in alphabetical order.

**Comment by kmcostel** [comment]
Regions include: APAC (Australia, Japan, Philippines, SE Asia), EMEA (BeNeLuxNord, DACH, France, Intl Govts, UKI), North America (East, Midwest, NYM, SouthEast, West)

**Comment by dmcassel** [comment]
Will you be doing the top-level regions (APAC, EMEA, North America), lower-level, or both?
