### ISSUE TITLE
Deal with users that don't have a location

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#135]
Some ea users don't have a country, zip code, etc... This makes the geocoder return "null" as this ea users's coordinates. We should do something to them to show people that these ea users exist...

Could we dump them all in Antarctica or something? 😈

**Comment by dmcassel** [comment]
Give them a lat/long of 0/0. We'll declare the existence of "The Island Republic of MarkLogic", just off the coast of Africa.

**Comment by graceyin1218** [comment]
The Island Republic of MarkLogic has been founded. 🎏
