### ISSUE TITLE
"Provide Feedback" email feature in index.html

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#138]
Jim's suggestion, considered a "should"

**Comment by dmcassel** [comment]
When implemented, email should be sent to a list address, rather than to an individual. IT Helpdesk can set up the list.

**Comment by dmcassel** [comment]
The close button ("X") for the popup is missing.

**Comment by dmcassel** [comment]
The missing close button is addressed in another issue.
