### ISSUE TITLE
Ingest data from #19 into MarkLogic

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#20]
#19 . Note: Adding new data into MarkLogic should cause triggers to fire and for module from #8 to run.

**Comment by graceyin1218** [comment]
Could either ingest data through ml local deploy content, or run initData_REST.sjs followed by updateData_REST.sjs (which should be a recurring task)

(Just FYI : initData_REST.sjs just ingests all the EA1 users. updateData_REST.sjs ingests all the EA2 users. We can easily change updateData_REST.sjs to ingest EA3 users when EA3 comes out and the EA2 list of users no longer changes.)
