### ISSUE TITLE
Add facet on EA version

### ISSUE THREAD

**Issue by dmcassel** [marklogic/eauser-geomapper#219]

**Comment by popzip** [comment]
+1 
(is there a different way to systematically upvote?)

**Comment by jamesclarksm** [comment]
+1

**Comment by jamesclarksm** [comment]
FACETS!!!

**Comment by dmcassel** [comment]
@popzip +1 comments work. I don't think GitHub offers any more general way.

**Comment by dmcassel** [comment]
Done & deployed

**Comment by popzip** [comment]
This is great, very helpful thanks.
