### ISSUE TITLE
Update task overwrites submitted content

### ISSUE THREAD

**Issue by dmcassel** [marklogic/eauser-geomapper#223]
Both "features" and "customNotes" are inside of "fullDetails". The current update process overwrites fullDetails when it gets data from Marketo.

**Comment by popzip** [comment]
Thanks. Other question still stands as you dig in - how does the data model work, is the update tied to an EA Version-specific Customer record? Such as EA2-Kasey may have Optic marked but EA3-Kasey would not necessarily?

**Comment by dmcassel** [comment]
As it stands, the customNotes thing is a single thing, not based on who wrote it or what version it's tied to. If you'd like to see changes, please do file that.

**Comment by popzip** [comment]
Nope no change right now just trying to understand behavior for searchability. is it a separate document?

**Comment by dmcassel** [comment]
The note is part of the user doc.

**Comment by popzip** [comment]
Ohh. I wasn't asking about Kasey as a TEACUP user but as a EA customer. Like is each EA user 1 record "Employee X from Company ABC" or could an EA user by many records:

- "Employee X from Company ABC - EA1 version"
- "Employee X from Company ABC - EA2 version"

**Comment by dmcassel** [comment]
fixed & deployed

**Comment by dmcassel** [comment]
Each user document in the database has a property listing versions:

    ea_versions: ['EA2', 'EA3']

Each EA account becomes one document in TEACUP's database.
