### ISSUE TITLE
Make the map prettier

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#36]
Add some color and geographical detail.

Right now it looks grey and sad :(

**Comment by graceyin1218** [comment]
Question:

Should we hide Danica's mapbox access token in the private folder?

**Comment by graceyin1218** [comment]
Possible tileLayers can be found here: https://leaflet-extras.github.io/leaflet-providers/preview/ 

(I just picked the first one. It was the layer with the most English, I think.)

**Comment by dmcassel** [comment]
Yes, access tokens should be hidden in the src/private folder. When you add it there, also edit the README there to point to or provide instructions on how to get an access token.

**Comment by graceyin1218** [comment]
Ok, it's now colorful, and is almost entirely in English (if you zoom in too much, for example, in China, some things are obviously not in English..)

If we want to change things later, we can do so through Mapbox. 😁 <- There are emojis❗
