### ISSUE TITLE
Create a collation to bypass case-sensitive user inputs

### ISSUE THREAD

**Issue by liangdanica** [marklogic/eauser-geomapper#44]

**Comment by dmcassel** [comment]
To do this, you'll update the specification of the range index in ml-config.xml, then run "ml local bootstrap".

**Comment by liangdanica** [comment]
In the ml-config.xml file, I changed every collation tag within the range element indexes to 'http://marklogic.com/collation/enS1'. Please let me know if you would like to me to push my changes. It feels like a minor change, so I haven't pushed.

**Comment by dmcassel** [comment]
Let's not close until the code is pushed, reviewed, and merged. The other way we might close a ticket is if we decide not to do it.

**Comment by liangdanica** [comment]
Okay, should I push my changes?

**Comment by dmcassel** [comment]
Yes
