### ISSUE TITLE
Parse data received from Marketo

### ISSUE THREAD

**Issue by graceyin1218** [marklogic/eauser-geomapper#45]
Marketo gives data as a list of leadRecords. Need to skim through each leadRecord individually and determine whether or not it represents an EA user. If yes, we need to reformat it into json.

Along the way, 'twould be nice to keep track of what industries exist.

**Comment by dmcassel** [comment]
If industry is part of the user records you'll create, then the way to get the list of industries will be calling [cts.values()](http://docs.marklogic.com/cts.values) on a range index of industries.

**Comment by kmcostel** [comment]
Why not use facets?

**Comment by dmcassel** [comment]
Under the hood, cts.values() is how facets are generated. If you programmatically needed a list of industries, you could call that function to get the list. But more likely, you'll have jsearch return a facet, yes.
