### ISSUE TITLE
Add sample data to project in eauser-geomapper/data

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#47]

**Comment by dmcassel** [comment]
You can put some data in a directory called "data", then either use `ml local deploy content` or you check in an [MLCP options file](http://docs.marklogic.com/guide/mlcp/intro#id_36150).

**Comment by dmcassel** [comment]
Since the sample data will be on GitHub, ensure that it is properly anonymized.

**Comment by kmcostel** [comment]
It is data created from json-generator.com, data should have no real meaning.

**Comment by dmcassel** [comment]
Does the generated data match the structure of the real data?

**Comment by kmcostel** [comment]
Yes, the response from Marketo is being transformed to fit the same structure as the fake data. It is in GeoJSON format.
