### ISSUE TITLE
Show markers on map to reflect the features used by the EA user

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#49]
Ex. users who mainly use bitemporal will have a bitemporal icon as their marker on map.

**Comment by liangdanica** [comment]
The markers can also possibly reflect new users within a certain period of time (eg. last 24 hours).

**Comment by dmcassel** [comment]
You've described two dimensions of information -- features and recency. Think about how to reflect each. You might use shape for features and color for time.

**Comment by kmcostel** [comment]
Won't implement
