### ISSUE TITLE
Manual input feature - create a pop-up "form" allowing for people to manually update things

### ISSUE THREAD

**Issue by liangdanica** [marklogic/eauser-geomapper#54]
This a form that allows the person viewing the map to manually add updates/notes/etc. In other words, this is like a repository of notes and feedback gathered about this specific user. Would be helpful for PM team!

For example, when a specific user asks a question on the forum, a PM person can manually edit and be able to help keep track of users who have been most active in the forums.

**Comment by kmcostel** [comment]
Create a button in marker popup's to open this "form"

**Comment by kmcostel** [comment]
The main reason for this issue is so that the user of this app is able to add/delete features to keep track of what the ea user uses. The only field editable to the user shall be the ability to add/remove features since this data doesn't come from Marketo.

**Comment by kmcostel** [comment]
This will not be implemented. Only the details page will have ability to edit user features. Only certain user roles should be able to access the details page. Everything on the map page should be view only.
