### ISSUE TITLE
Write function to update properties of GeoJSON object

### ISSUE THREAD

**Issue by liangdanica** [marklogic/eauser-geomapper#59]
This function will overwrite/update GEOJSON objects with new data, whether it be:
- manually inputted (#36)
- extracted from email crawl (#37)

**Comment by graceyin1218** [comment]
We need to be careful about keeping a record of when the document was first added to the database (so we know who the new users are).

@dmcassel - is there a way to update certain fields in a document? Or will we have to completely overwrite it every time we want to update it?

**Comment by dmcassel** [comment]
Yes, you can selectively update a document. You can either use functions like [xdmp.nodeReplace](http://docs.marklogic.com/xdmp.nodeReplace), [xdmp.nodeInsertAfter](http://docs.marklogic.com/xdmp.nodeInsertAfter), [xdmp.nodeInsertBefore](http://docs.marklogic.com/xdmp.nodeInsertBefore), and [xdmp.nodeInsertChild](http://docs.marklogic.com/xdmp.nodeInsertChild), or you can load the file, use .toObject() to get a regular JS object, make your updates, and write it back to the database, as illustrated in the [Server-side JavaScript tutorial](http://developer.marklogic.com/learn/sjs/update).

**Comment by kmcostel** [comment]
This looks like it would do what #61 would do, so will close #61 for now.

**Comment by graceyin1218** [comment]
Updating Marketo-related data is complete. Features are still on standby.
