### ISSUE TITLE
Add document to /data to contain all ML 9 features.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#62]
Use this document for providing the ML features to the web page.

**Comment by dmcassel** [comment]
I suggest putting this file under data/config/ and others under data/content. That way, your queries can exclude the config file.

**Comment by kmcostel** [comment]
If placed in config/ then it wouldn't live in database?

**Comment by dmcassel** [comment]
When we put config data into the database, then yes, we want to segment it off from regular content. Putting it in /data/config/ (and other stuff into /data/content/) means that we can do a directory query to focus on what we want to see.

**Comment by kmcostel** [comment]
TODO: Talk with Jim to get full list of ML features

**Comment by kmcostel** [comment]
No feature data for any user yet, so no need for this yet.

**Comment by kmcostel** [comment]
Full features as of 8/8/2016 for ML9 in project.
