### ISSUE TITLE
Add a search button to the web page.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#63]
On click, update the map to reflect the selected facets. Example: If industry A and B are selected and Feature 1 is selected, find users that match one of the industry selections, who also use Feature 1 of ML.

**Comment by dmcassel** [comment]
There are multiple events that should trigger a search, typically:

- creating a new geo region on the map
- selecting a facet value
- clicking the search button next to the text search box

**Comment by kmcostel** [comment]
Rely on above triggers to perform searches
