### ISSUE TITLE
Change layout of /index.html

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#64]
Implement the design changes Mitch talked about. Reference Danica's notepad.

This will be a more time consuming ticket, don't let the short description fool you.
Essentially, menus to select features and industry will be on left side of page and vertically stacked on each other.

**Comment by kmcostel** [comment]
This will be a more time consuming ticket, don't let the short description fool you.

**Comment by graceyin1218** [comment]
renamed map.html to index.html
