### ISSUE TITLE
Figure out all MarkLogic features and add to MLFeatures.json in the database

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#66]

**Comment by graceyin1218** [comment]
Wait, what will we use MLFeatures.json for?

**Comment by kmcostel** [comment]
It will be used to populate menus that show all ML features. I think we need this document because there is no where else to find all of MarkLogic's features.

**Comment by graceyin1218** [comment]
Doesn't the thing Danica did earlier today (the thing where you have a list of features and how many matches there are) fulfill the purpose of displaying all features? (If we zoom out to see the whole world and display the search results from that view?)

**Comment by kmcostel** [comment]
We need some way of knowing all MarkLogic features; the idea is to show all of MarkLogic's features even if some of them are not used by anyone. Right now we are taking features from the fake data and assuming those are all possible features, the real data may not (probably won't) have all of MarkLogic's features.

**Comment by kmcostel** [comment]
Source of features: http://ea.marklogic.com/
