### ISSUE TITLE
UI - Change the layout of the selection menus

### ISSUE THREAD

**Issue by liangdanica** [marklogic/eauser-geomapper#70]
A more detailed write-up of #64:
- scrolling list of checkbox items, one for industries and one for features, stacked on top of one another
- a 'clear' feature for each list to clear features/industries (Mitch suggested a trash can icon next to the name -- should be foundas part of the Bootstrap glyphicons)
- We should be able to see the checked boxes on the resting state of the page
- Possibly another menu at the bottom that lists everything that was selected. We can put a clear or reset button here as well?

**Comment by dmcassel** [comment]
When looking for icons, check [Bootstrap glyphicons](http://getbootstrap.com/components/#glyphicons).
