### ISSUE TITLE
Refactor search.sjs to be able to combine industry, feature, and geo queries to find users.

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#79]
Need to use cts to combine queries, so switch jsearch searches with cts. queries

**Comment by dmcassel** [comment]
Why not something like this? 

    var users = 
      jsearch.facets([
          jsearch.facet('Industry', cts.jsonPropertyReference('industry')).orderBy('frequency', 'descending'),
          jsearch.facet('Feature', cts.jsonPropertyReference('features')).orderBy('frequency', 'descending'),
        ],
        jsearch.documents().map({extract:{select:'all'}})
      )
      .where(
        cts.andQuery([
          industryQuery,
          featureQuery,
          geoQuery
        ])
      )
      .result();

That lets the JSearch library handle the facet generation for you.
