### ISSUE TITLE
Alert feature for new Users, write module

### ISSUE THREAD

**Issue by kmcostel** [marklogic/eauser-geomapper#8]
Write a module in .sjs for the action the alert should perform when new users are discovered.

Probably some visual change in the map.

**Comment by graceyin1218** [comment]
All users have a "dateAdded" field that contains the date they were added to our MarkLogic database. 

Using that date, it would be possible to pick out new ea users and color them differently.

**Comment by graceyin1218** [comment]
The "alert" will be in the email updates.
