### ISSUE TITLE
Create facet menu for company names

### ISSUE THREAD

**Issue by liangdanica** [marklogic/eauser-geomapper#89]
Probably would make the most sense to order alphabetically too.

**Comment by kmcostel** [comment]
Why not ordered by count?

**Comment by liangdanica** [comment]
I assumed that there would only be only one of each company (unless MarkLogic maybe lol). And also I was just thinking in the case that someone had a specific company they are looking for, it would be easier to find if everything is alphabetized. What are your thoughts?
